### ISSUE TITLE
mqtt.js:108 Uncaught ReferenceError: True is not defined

### ISSUE THREAD

**Issue by hoetzgit** [bellrichm/weewx-jas#53]
Rich, this error appears for me in the Chrome Developer View. With `useSSL = true` it works.
Could you adjust it to accept all spellings of "True" in the template?

```
mqtt.js:108 Uncaught ReferenceError: True is not defined
    at MQTTConnect (mqtt.js:108:17)
    at index.js:129:5
MQTTConnect @ mqtt.js:108

```
weewx.conf:
```
            [[[[mqtt]]]]
                enable = True
                
                host = xxx
                port = 443
                
                useSSL = True
                
                username = REPLACE_ME
                password = REPLACE_ME
                
                topic = weewx/loop
```
Henry

**Comment by bellrichm** [comment]
This is due to javascript booleans being lower case. I am in the process of forcing them to lower case. In the meantime try
```
useSSL = true
```

**Comment by hoetzgit** [comment]
this commit has fixed the "error". Thanks a lot
